delete policy large-community-list FROM-DOWNSTREAM
set policy large-community-list FROM-DOWNSTREAM rule 10 action 'permit'
set policy large-community-list FROM-DOWNSTREAM rule 10 regex '%ASN%:0:500'

delete policy large-community-list FROM-IBGP
set policy large-community-list FROM-IBGP rule 10 action 'permit'
set policy large-community-list FROM-IBGP rule 10 regex '%ASN%:0:100'

delete policy large-community-list FROM-LOCAL-AS
set policy large-community-list FROM-LOCAL-AS rule 10 action 'permit'
set policy large-community-list FROM-LOCAL-AS rule 10 regex '%ASN%:0:10'

delete policy large-community-list FROM-PEER
set policy large-community-list FROM-PEER rule 10 action 'permit'
set policy large-community-list FROM-PEER rule 10 regex '%ASN%:0:400'

delete policy large-community-list FROM-ROUTESERVER
set policy large-community-list FROM-ROUTESERVER rule 10 action 'permit'
set policy large-community-list FROM-ROUTESERVER rule 10 regex '%ASN%:0:300'

delete policy large-community-list FROM-UPSTREAM
set policy large-community-list FROM-UPSTREAM rule 10 action 'permit'
set policy large-community-list FROM-UPSTREAM rule 10 regex '%ASN%:0:200'

delete policy prefix-list Bogons-IPv4
set policy prefix-list Bogons-IPv4 rule 10 action 'permit'
set policy prefix-list Bogons-IPv4 rule 10 description 'RFC 1918 private space'
set policy prefix-list Bogons-IPv4 rule 10 le '32'
set policy prefix-list Bogons-IPv4 rule 10 prefix '0.0.0.0/8'
set policy prefix-list Bogons-IPv4 rule 20 action 'permit'
set policy prefix-list Bogons-IPv4 rule 20 description 'RFC 1918 private space'
set policy prefix-list Bogons-IPv4 rule 20 le '32'
set policy prefix-list Bogons-IPv4 rule 20 prefix '10.0.0.0/8'
set policy prefix-list Bogons-IPv4 rule 30 action 'permit'
set policy prefix-list Bogons-IPv4 rule 30 description 'RFC 6598 Carrier grade nat space'
set policy prefix-list Bogons-IPv4 rule 30 le '32'
set policy prefix-list Bogons-IPv4 rule 30 prefix '100.64.0.0/10'
set policy prefix-list Bogons-IPv4 rule 40 action 'permit'
set policy prefix-list Bogons-IPv4 rule 40 description 'RFC 1122 localhost'
set policy prefix-list Bogons-IPv4 rule 40 le '32'
set policy prefix-list Bogons-IPv4 rule 40 prefix '127.0.0.0/8'
set policy prefix-list Bogons-IPv4 rule 50 action 'permit'
set policy prefix-list Bogons-IPv4 rule 50 description 'RFC 3927 link local'
set policy prefix-list Bogons-IPv4 rule 50 le '32'
set policy prefix-list Bogons-IPv4 rule 50 prefix '169.254.0.0/16'
set policy prefix-list Bogons-IPv4 rule 60 action 'permit'
set policy prefix-list Bogons-IPv4 rule 60 description 'RFC 1918 private space '
set policy prefix-list Bogons-IPv4 rule 60 le '32'
set policy prefix-list Bogons-IPv4 rule 60 prefix '172.16.0.0/12'
set policy prefix-list Bogons-IPv4 rule 70 action 'permit'
set policy prefix-list Bogons-IPv4 rule 70 description 'RFC 5736 IETF Protocol Assignments'
set policy prefix-list Bogons-IPv4 rule 70 le '32'
set policy prefix-list Bogons-IPv4 rule 70 prefix '192.0.0.0/24'
set policy prefix-list Bogons-IPv4 rule 80 action 'permit'
set policy prefix-list Bogons-IPv4 rule 80 description 'RFC 5737 TEST-NET-1'
set policy prefix-list Bogons-IPv4 rule 80 le '32'
set policy prefix-list Bogons-IPv4 rule 80 prefix '192.0.2.0/24'
set policy prefix-list Bogons-IPv4 rule 90 action 'permit'
set policy prefix-list Bogons-IPv4 rule 90 description 'RFC 7526 6to4 anycast relay'
set policy prefix-list Bogons-IPv4 rule 90 le '32'
set policy prefix-list Bogons-IPv4 rule 90 prefix '192.88.99.0/24'
set policy prefix-list Bogons-IPv4 rule 100 action 'permit'
set policy prefix-list Bogons-IPv4 rule 100 description 'RFC 1918 private space'
set policy prefix-list Bogons-IPv4 rule 100 le '32'
set policy prefix-list Bogons-IPv4 rule 100 prefix '192.168.0.0/16'
set policy prefix-list Bogons-IPv4 rule 110 action 'permit'
set policy prefix-list Bogons-IPv4 rule 110 description 'RFC 2544 benchmarking'
set policy prefix-list Bogons-IPv4 rule 110 le '32'
set policy prefix-list Bogons-IPv4 rule 110 prefix '198.18.0.0/15'
set policy prefix-list Bogons-IPv4 rule 120 action 'permit'
set policy prefix-list Bogons-IPv4 rule 120 description 'RFC 5737 TEST-NET-2'
set policy prefix-list Bogons-IPv4 rule 120 le '32'
set policy prefix-list Bogons-IPv4 rule 120 prefix '198.51.100.0/24'
set policy prefix-list Bogons-IPv4 rule 130 action 'permit'
set policy prefix-list Bogons-IPv4 rule 130 description 'RFC 5737 TEST-NET-3'
set policy prefix-list Bogons-IPv4 rule 130 le '32'
set policy prefix-list Bogons-IPv4 rule 130 prefix '203.0.113.0/24'
set policy prefix-list Bogons-IPv4 rule 140 action 'permit'
set policy prefix-list Bogons-IPv4 rule 140 description 'multicast'
set policy prefix-list Bogons-IPv4 rule 140 le '32'
set policy prefix-list Bogons-IPv4 rule 140 prefix '224.0.0.0/4'
set policy prefix-list Bogons-IPv4 rule 150 action 'permit'
set policy prefix-list Bogons-IPv4 rule 150 description 'RFC 5771 MCAST-TEST-NET'
set policy prefix-list Bogons-IPv4 rule 150 le '32'
set policy prefix-list Bogons-IPv4 rule 150 prefix '233.252.0.0/24'
set policy prefix-list Bogons-IPv4 rule 160 action 'permit'
set policy prefix-list Bogons-IPv4 rule 160 description 'reserved'
set policy prefix-list Bogons-IPv4 rule 160 le '32'
set policy prefix-list Bogons-IPv4 rule 160 prefix '240.0.0.0/4'
set policy prefix-list Bogons-IPv4 rule 170 action 'permit'
set policy prefix-list Bogons-IPv4 rule 170 description 'Limited Broadcast'
set policy prefix-list Bogons-IPv4 rule 170 prefix '255.255.255.255/32'
set policy prefix-list Bogons-IPv4 rule 180 action 'permit'
set policy prefix-list Bogons-IPv4 rule 180 description 'Default route'
set policy prefix-list Bogons-IPv4 rule 180 prefix '0.0.0.0/0'

delete policy prefix-list IPv4-ALL
set policy prefix-list IPv4-ALL rule 10 action 'permit'
set policy prefix-list IPv4-ALL rule 10 ge '0'
set policy prefix-list IPv4-ALL rule 10 le '32'
set policy prefix-list IPv4-ALL rule 10 prefix '0.0.0.0/0'

delete policy prefix-list IPv4-Range-0to7
set policy prefix-list IPv4-Range-0to7 rule 10 action 'permit'
set policy prefix-list IPv4-Range-0to7 rule 10 description 'Match IPv4 block bigger than /8'
set policy prefix-list IPv4-Range-0to7 rule 10 ge '0'
set policy prefix-list IPv4-Range-0to7 rule 10 le '7'
set policy prefix-list IPv4-Range-0to7 rule 10 prefix '0.0.0.0/0'

delete policy prefix-list IPv4-Range-25to32
set policy prefix-list IPv4-Range-25to32 rule 10 action 'permit'
set policy prefix-list IPv4-Range-25to32 rule 10 description 'Match IPv4 block smaller than /24'
set policy prefix-list IPv4-Range-25to32 rule 10 ge '25'
set policy prefix-list IPv4-Range-25to32 rule 10 le '32'
set policy prefix-list IPv4-Range-25to32 rule 10 prefix '0.0.0.0/0'

delete policy prefix-list LOCAL-ALLOWED-PREFIX4
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 10 action 'permit'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 10 description 'ipv4 bogons used in my network'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 10 le '32'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 10 prefix '10.203.0.0/16'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 20 action 'permit'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 20 description 'ipv4 bogons with AP'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 20 ge '24'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 20 le '24'
set policy prefix-list LOCAL-ALLOWED-PREFIX4 rule 20 prefix '192.168.0.0/16'

delete policy prefix-list6 Bogons-IPv6
set policy prefix-list6 Bogons-IPv6 rule 10 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 10 description 'Unspecified address'
set policy prefix-list6 Bogons-IPv6 rule 10 prefix '::/128'
set policy prefix-list6 Bogons-IPv6 rule 20 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 20 description 'Loopback address'
set policy prefix-list6 Bogons-IPv6 rule 20 prefix '::1/128'
set policy prefix-list6 Bogons-IPv6 rule 30 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 30 description 'IPv4-mapped addresses'
set policy prefix-list6 Bogons-IPv6 rule 30 le '128'
set policy prefix-list6 Bogons-IPv6 rule 30 prefix '::ffff:0:0/96'
set policy prefix-list6 Bogons-IPv6 rule 40 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 40 description 'IPv4 translated addresses'
set policy prefix-list6 Bogons-IPv6 rule 40 le '128'
set policy prefix-list6 Bogons-IPv6 rule 40 prefix '::ffff:0:0:0/96'
set policy prefix-list6 Bogons-IPv6 rule 50 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 50 description 'IPv4/IPv6 translation'
set policy prefix-list6 Bogons-IPv6 rule 50 le '128'
set policy prefix-list6 Bogons-IPv6 rule 50 prefix '64:ff9b::/96'
set policy prefix-list6 Bogons-IPv6 rule 60 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 60 description 'IPv4/IPv6 translation'
set policy prefix-list6 Bogons-IPv6 rule 60 le '128'
set policy prefix-list6 Bogons-IPv6 rule 60 prefix '64:ff9b:1::/48'
set policy prefix-list6 Bogons-IPv6 rule 70 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 70 description 'Discard prefix'
set policy prefix-list6 Bogons-IPv6 rule 70 le '128'
set policy prefix-list6 Bogons-IPv6 rule 70 prefix '100::/64'
set policy prefix-list6 Bogons-IPv6 rule 80 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 80 description 'Teredo tunneling'
set policy prefix-list6 Bogons-IPv6 rule 80 le '128'
set policy prefix-list6 Bogons-IPv6 rule 80 prefix '2001:0000::/32'
set policy prefix-list6 Bogons-IPv6 rule 90 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 90 description 'ORCHIDv2'
set policy prefix-list6 Bogons-IPv6 rule 90 le '128'
set policy prefix-list6 Bogons-IPv6 rule 90 prefix '2001:20::/28'
set policy prefix-list6 Bogons-IPv6 rule 100 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 100 description 'Addresses used in documentation and example source code'
set policy prefix-list6 Bogons-IPv6 rule 100 le '128'
set policy prefix-list6 Bogons-IPv6 rule 100 prefix '2001:db8::/32'
set policy prefix-list6 Bogons-IPv6 rule 110 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 110 description 'The 6to4 addressing scheme (deprecated)'
set policy prefix-list6 Bogons-IPv6 rule 110 le '128'
set policy prefix-list6 Bogons-IPv6 rule 110 prefix '2002::/16'
set policy prefix-list6 Bogons-IPv6 rule 120 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 120 description 'RFC 4193 unique local unicast'
set policy prefix-list6 Bogons-IPv6 rule 120 le '128'
set policy prefix-list6 Bogons-IPv6 rule 120 prefix 'fc00::/7'
set policy prefix-list6 Bogons-IPv6 rule 130 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 130 description 'RFC 4291 link local unicast'
set policy prefix-list6 Bogons-IPv6 rule 130 le '128'
set policy prefix-list6 Bogons-IPv6 rule 130 prefix 'fe80::/10'
set policy prefix-list6 Bogons-IPv6 rule 140 action 'permit'
set policy prefix-list6 Bogons-IPv6 rule 140 description 'RFC 4291 multicast'
set policy prefix-list6 Bogons-IPv6 rule 140 le '128'
set policy prefix-list6 Bogons-IPv6 rule 140 prefix 'ff00::/8'

delete policy prefix-list6 IPv6-ALL
set policy prefix-list6 IPv6-ALL rule 10 action 'permit'
set policy prefix-list6 IPv6-ALL rule 10 ge '0'
set policy prefix-list6 IPv6-ALL rule 10 le '128'
set policy prefix-list6 IPv6-ALL rule 10 prefix '::/0'

delete policy prefix-list6 IPv6-Range-0to15
set policy prefix-list6 IPv6-Range-0to15 rule 10 action 'permit'
set policy prefix-list6 IPv6-Range-0to15 rule 10 description 'Match IPv6 block bigger than /16'
set policy prefix-list6 IPv6-Range-0to15 rule 10 ge '0'
set policy prefix-list6 IPv6-Range-0to15 rule 10 le '15'
set policy prefix-list6 IPv6-Range-0to15 rule 10 prefix '::/0'

delete policy prefix-list6 IPv6-Range-49to128
set policy prefix-list6 IPv6-Range-49to128 rule 10 action 'permit'
set policy prefix-list6 IPv6-Range-49to128 rule 10 description 'Match IPv6 block smaller than /48'
set policy prefix-list6 IPv6-Range-49to128 rule 10 ge '49'
set policy prefix-list6 IPv6-Range-49to128 rule 10 le '128'
set policy prefix-list6 IPv6-Range-49to128 rule 10 prefix '::/0'

delete policy prefix-list6 LOCAL-ALLOWED-PREFIX6
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 10 action 'permit'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 10 description 'ipv6 bogons used in my network'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 10 le '128'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 10 prefix 'fd00:20:3023::/48'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 20 action 'permit'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 20 description 'ipv6 bogons with AP'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 20 ge '64'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 20 le '64'
set policy prefix-list6 LOCAL-ALLOWED-PREFIX6 rule 20 prefix 'fd00:192:168::/48'

delete policy route-map DOWNSTREAM-IN
set policy route-map DOWNSTREAM-IN rule 10 action 'permit'
set policy route-map DOWNSTREAM-IN rule 10 call 'FILTER-EBGP'
set policy route-map DOWNSTREAM-IN rule 10 on-match next
set policy route-map DOWNSTREAM-IN rule 20 action 'permit'
set policy route-map DOWNSTREAM-IN rule 20 set large-community add '%ASN%:0:500'
set policy route-map DOWNSTREAM-IN rule 20 set local-preference '200'

delete policy route-map DOWNSTREAM-OUT
set policy route-map DOWNSTREAM-OUT rule 1 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 1 match protocol 'static'
set policy route-map DOWNSTREAM-OUT rule 1 on-match goto '110'
set policy route-map DOWNSTREAM-OUT rule 26 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 26 match large-community large-community-list 'FROM-IBGP'
set policy route-map DOWNSTREAM-OUT rule 26 on-match goto '110'
set policy route-map DOWNSTREAM-OUT rule 27 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 27 match large-community large-community-list 'FROM-UPSTREAM'
set policy route-map DOWNSTREAM-OUT rule 27 on-match goto '110'
set policy route-map DOWNSTREAM-OUT rule 28 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 28 match large-community large-community-list 'FROM-ROUTESERVER'
set policy route-map DOWNSTREAM-OUT rule 28 on-match goto '110'
set policy route-map DOWNSTREAM-OUT rule 29 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 29 match large-community large-community-list 'FROM-PEER'
set policy route-map DOWNSTREAM-OUT rule 29 on-match goto '110'
set policy route-map DOWNSTREAM-OUT rule 30 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 30 match large-community large-community-list 'FROM-DOWNSTREAM'
set policy route-map DOWNSTREAM-OUT rule 30 on-match goto '110'
set policy route-map DOWNSTREAM-OUT rule 100 action 'deny'
set policy route-map DOWNSTREAM-OUT rule 110 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 110 call 'FILTER-EBGP'
set policy route-map DOWNSTREAM-OUT rule 110 on-match next
set policy route-map DOWNSTREAM-OUT rule 120 action 'permit'
set policy route-map DOWNSTREAM-OUT rule 120 set large-community delete 'FROM-IBGP'

delete policy route-map FILTER-EBGP
set policy route-map FILTER-EBGP rule 10 action 'permit'
set policy route-map FILTER-EBGP rule 10 call 'REJECT-BOGONS'
set policy route-map FILTER-EBGP rule 10 on-match next
set policy route-map FILTER-EBGP rule 20 action 'permit'
set policy route-map FILTER-EBGP rule 20 call 'FILTER-RPKI'

delete policy route-map FILTER-IBGP
set policy route-map FILTER-IBGP rule 10 action 'permit'
set policy route-map FILTER-IBGP rule 10 match ip address prefix-list 'LOCAL-ALLOWED-PREFIX4'
set policy route-map FILTER-IBGP rule 20 action 'permit'
set policy route-map FILTER-IBGP rule 20 match ip address prefix-list 'LOCAL-ASN-PREFIX4'
set policy route-map FILTER-IBGP rule 30 action 'permit'
set policy route-map FILTER-IBGP rule 30 match ipv6 address prefix-list 'LOCAL-ALLOWED-PREFIX6'
set policy route-map FILTER-IBGP rule 40 action 'permit'
set policy route-map FILTER-IBGP rule 50 match ipv6 address prefix-list 'LOCAL-ASN-PREFIX6'
set policy route-map FILTER-IBGP rule 100 action 'permit'
set policy route-map FILTER-IBGP rule 100 call 'REJECT-BOGONS'

delete policy route-map FILTER-RPKI
set policy route-map FILTER-RPKI rule 10 action 'permit'
set policy route-map FILTER-RPKI rule 10 match rpki 'valid'
set policy route-map FILTER-RPKI rule 20 action 'permit'
set policy route-map FILTER-RPKI rule 20 match rpki 'notfound'
set policy route-map FILTER-RPKI rule 30 action 'deny'
set policy route-map FILTER-RPKI rule 30 match rpki 'invalid'

delete policy route-map IBGP-IN
set policy route-map IBGP-IN rule 10 action 'permit'
set policy route-map IBGP-IN rule 10 call 'FILTER-IBGP'
set policy route-map IBGP-IN rule 10 on-match next
set policy route-map IBGP-IN rule 20 action 'permit'
set policy route-map IBGP-IN rule 20 set large-community add '%ASN%:0:100'
set policy route-map IBGP-IN rule 20 set local-preference '90'

delete policy route-map IBGP-OUT
set policy route-map IBGP-OUT rule 110 action 'permit'
set policy route-map IBGP-OUT rule 110 call 'FILTER-IBGP'
set policy route-map IBGP-OUT rule 110 on-match next
set policy route-map IBGP-OUT rule 120 action 'permit'
set policy route-map IBGP-OUT rule 120 set large-community delete 'FROM-IBGP'

delete policy route-map PEER-IN
set policy route-map PEER-IN rule 10 action 'permit'
set policy route-map PEER-IN rule 10 call 'FILTER-EBGP'
set policy route-map PEER-IN rule 10 on-match next
set policy route-map PEER-IN rule 20 action 'permit'
set policy route-map PEER-IN rule 20 set large-community add '%ASN%:0:400'
set policy route-map PEER-IN rule 20 set local-preference '160'

delete policy route-map PEER-OUT
set policy route-map PEER-OUT rule 1 action 'permit'
set policy route-map PEER-OUT rule 1 match protocol 'static'
set policy route-map PEER-OUT rule 1 on-match goto '110'
set policy route-map PEER-OUT rule 30 action 'permit'
set policy route-map PEER-OUT rule 30 match large-community large-community-list 'FROM-DOWNSTREAM'
set policy route-map PEER-OUT rule 30 on-match goto '110'
set policy route-map PEER-OUT rule 100 action 'deny'
set policy route-map PEER-OUT rule 110 action 'permit'
set policy route-map PEER-OUT rule 110 call 'FILTER-EBGP'
set policy route-map PEER-OUT rule 110 on-match next
set policy route-map PEER-OUT rule 120 action 'permit'
set policy route-map PEER-OUT rule 120 set large-community delete 'FROM-IBGP'

delete policy route-map REJECT-ALL
set policy route-map REJECT-ALL rule 10 action 'deny'

delete policy route-map REJECT-BOGONS
set policy route-map REJECT-BOGONS description 'Reject bogon ASNs and route prefixes.'
set policy route-map REJECT-BOGONS rule 10 action 'deny'
set policy route-map REJECT-BOGONS rule 10 match ip address prefix-list 'IPv4-Range-0to7'
set policy route-map REJECT-BOGONS rule 11 action 'deny'
set policy route-map REJECT-BOGONS rule 11 match ip address prefix-list 'IPv4-Range-25to32'
set policy route-map REJECT-BOGONS rule 20 action 'deny'
set policy route-map REJECT-BOGONS rule 20 match ipv6 address prefix-list 'IPv6-Range-0to15'
set policy route-map REJECT-BOGONS rule 21 action 'deny'
set policy route-map REJECT-BOGONS rule 21 match ipv6 address prefix-list 'IPv6-Range-49to128'
set policy route-map REJECT-BOGONS rule 30 action 'deny'
set policy route-map REJECT-BOGONS rule 30 description 'Reject routes with bogon AS numbers in the as-path'
set policy route-map REJECT-BOGONS rule 30 match as-path 'Bogons-ASN'
set policy route-map REJECT-BOGONS rule 40 action 'deny'
set policy route-map REJECT-BOGONS rule 40 description 'Reject bogon IPv4 prefixes'
set policy route-map REJECT-BOGONS rule 40 match ip address prefix-list 'Bogons-IPv4'
set policy route-map REJECT-BOGONS rule 50 action 'deny'
set policy route-map REJECT-BOGONS rule 50 description 'Reject bogon IPv6 prefixes'
set policy route-map REJECT-BOGONS rule 50 match ipv6 address prefix-list 'Bogons-IPv6'
set policy route-map REJECT-BOGONS rule 100 action 'permit'

delete policy route-map ROUTESERVER-IN
set policy route-map ROUTESERVER-IN rule 10 action 'permit'
set policy route-map ROUTESERVER-IN rule 10 call 'FILTER-EBGP'
set policy route-map ROUTESERVER-IN rule 10 on-match next
set policy route-map ROUTESERVER-IN rule 20 action 'permit'
set policy route-map ROUTESERVER-IN rule 20 set large-community add '%ASN%:0:300'
set policy route-map ROUTESERVER-IN rule 20 set local-preference '130'

delete policy route-map ROUTESERVER-OUT
set policy route-map ROUTESERVER-OUT rule 1 action 'permit'
set policy route-map ROUTESERVER-OUT rule 1 match protocol 'static'
set policy route-map ROUTESERVER-OUT rule 1 on-match goto '110'
set policy route-map ROUTESERVER-OUT rule 30 action 'permit'
set policy route-map ROUTESERVER-OUT rule 30 match large-community large-community-list 'FROM-DOWNSTREAM'
set policy route-map ROUTESERVER-OUT rule 30 on-match goto '110'
set policy route-map ROUTESERVER-OUT rule 100 action 'deny'
set policy route-map ROUTESERVER-OUT rule 110 action 'permit'
set policy route-map ROUTESERVER-OUT rule 110 call 'FILTER-EBGP'
set policy route-map ROUTESERVER-OUT rule 110 on-match next
set policy route-map ROUTESERVER-OUT rule 120 action 'permit'
set policy route-map ROUTESERVER-OUT rule 120 set large-community delete 'FROM-IBGP'

delete policy route-map SIMPLE-IBGP-OUT
set policy route-map SIMPLE-IBGP-OUT rule 10 action 'permit'
set policy route-map SIMPLE-IBGP-OUT rule 10 match ip address prefix-list 'LOCAL-ALLOWED-PREFIX4'
set policy route-map SIMPLE-IBGP-OUT rule 20 action 'permit'
set policy route-map SIMPLE-IBGP-OUT rule 20 match ipv6 address prefix-list 'LOCAL-ALLOWED-PREFIX6'
set policy route-map SIMPLE-IBGP-OUT rule 30 action 'permit'
set policy route-map SIMPLE-IBGP-OUT rule 30 match ip address prefix-list 'LOCAL-ASN-PREFIX4'
set policy route-map SIMPLE-IBGP-OUT rule 40 action 'permit'
set policy route-map SIMPLE-IBGP-OUT rule 40 match ipv6 address prefix-list 'LOCAL-ASN-PREFIX6'

delete policy route-map UPSTREAM-IN
set policy route-map UPSTREAM-IN rule 10 action 'permit'
set policy route-map UPSTREAM-IN rule 10 call 'FILTER-EBGP'
set policy route-map UPSTREAM-IN rule 10 on-match next
set policy route-map UPSTREAM-IN rule 20 action 'permit'
set policy route-map UPSTREAM-IN rule 20 set large-community add '%ASN%:0:200'
set policy route-map UPSTREAM-IN rule 20 set local-preference '100'

delete policy route-map UPSTREAM-OUT
set policy route-map UPSTREAM-OUT rule 1 action 'permit'
set policy route-map UPSTREAM-OUT rule 1 match protocol 'static'
set policy route-map UPSTREAM-OUT rule 1 on-match goto '110'
set policy route-map UPSTREAM-OUT rule 30 action 'permit'
set policy route-map UPSTREAM-OUT rule 30 match large-community large-community-list 'FROM-DOWNSTREAM'
set policy route-map UPSTREAM-OUT rule 30 on-match goto '110'
set policy route-map UPSTREAM-OUT rule 100 action 'deny'
set policy route-map UPSTREAM-OUT rule 110 action 'permit'
set policy route-map UPSTREAM-OUT rule 110 call 'FILTER-EBGP'
set policy route-map UPSTREAM-OUT rule 110 on-match next
set policy route-map UPSTREAM-OUT rule 120 action 'permit'
set policy route-map UPSTREAM-OUT rule 120 set large-community delete 'FROM-IBGP'
