#!/bin/vbash

if [ "$(id -g -n)" != 'vyattacfg' ] ; then
    exec sg vyattacfg -c "/bin/vbash $(readlink -f $0) $@"
fi

source /opt/vyatta/etc/functions/script-template

ASN=27523
ROUTER=core.test.example

echo 'start configure (bird3)'

configure

set system host-name test-router


delete system sflow
set system sflow agent-address 192.0.2.254
set system sflow server 192.0.2.202 port 6343
set system sflow interface eth0
set system sflow interface eth1
set system sflow vpp
set vpp sflow interface eth2
set system sflow interface eth2
delete service snmp
set service snmp listen-address 192.0.2.254
set service snmp location 'LAB'
set service snmp v3 engineid 000000000000192000002254
set service snmp v3 group default mode ro
set service snmp v3 group default view default
set service snmp v3 user vyos auth encrypted-password encrypted
set service snmp v3 user vyos auth type sha
set service snmp v3 user vyos group default
set service snmp v3 user vyos privacy encrypted-password encrypted
set service snmp v3 user vyos privacy type aes
set service snmp v3 view default oid 1
delete container name bird
set container name bird image 'kawaiinetworks/bird:2'
set container name bird allow-host-networks
set container name bird capability 'net-admin'
set container name bird restart 'always'

set container name bird volume conf destination '/etc/bird'
set container name bird volume conf source '/config/myapp/bird'



set system login banner post-login 'generated by tests'

echo 'configure done'

commit

# Download generated BIRD configuration
mkdir -p /config/myapp/bird
curl -sSfLo /config/myapp/bird/bird.conf "https://worker.example/kawaii/as27523/router/bird.core.test.example.conf"

sudo podman exec bird birdcl configure || true
exit
