#!/bin/vbash

if [ "$(id -g -n)" != 'vyattacfg' ] ; then
    exec sg vyattacfg -c "/bin/vbash $(readlink -f $0) $@"
fi

source /opt/vyatta/etc/functions/script-template

ASN=27523
ROUTER=core.test.example

echo 'start configure'

configure

# update-config scheduler: refresh and re-apply this router's config every 12h.
if [ ! -d "/config/myapp" ]; then
    sudo mkdir -p /config/myapp
fi

sudo chown vyos -R /config/myapp

cat <<EOL > /config/myapp/update-config.sh
#!/bin/bash

wget -T 60 -O /config/myapp/configure.${ROUTER}.sh https://worker.example/kawaii/as27523/router/configure.${ROUTER}.sh
wget -T 60 -O /config/myapp/find_unused.py https://worker.example/kawaii/as27523/find_unused.py
vbash /config/myapp/configure.${ROUTER}.sh | tee /config/myapp/configure.log
rm /config/myapp/configure.${ROUTER}.sh
EOL

chmod +x /config/myapp/update-config.sh

delete system task-scheduler task update-config
set system task-scheduler task update-config executable path '/config/myapp/update-config.sh'
set system task-scheduler task update-config interval '12h'

delete system sflow
set system sflow agent-address 192.0.2.254
set system sflow server 192.0.2.202 port 6343
set system sflow interface eth0
set system sflow interface eth1
set system sflow vpp
set vpp sflow interface eth2
set system sflow interface eth2
delete service snmp
set service snmp listen-address 192.0.2.254
set service snmp location 'LAB'
set service snmp v3 engineid 000000000000192000002254
set service snmp v3 group default mode ro
set service snmp v3 group default view default
set service snmp v3 user vyos auth encrypted-password encrypted
set service snmp v3 user vyos auth type sha
set service snmp v3 user vyos group default
set service snmp v3 user vyos privacy encrypted-password encrypted
set service snmp v3 user vyos privacy type aes
set service snmp v3 view default oid 1
delete container name bird
set container name bird image 'kawaiinetworks/bird:2'
set container name bird allow-host-networks
set container name bird memory 0
set container name bird capability 'net-admin'
set container name bird restart 'always'

set container name bird command '-c /etc/bird/bird.conf -s /etc/bird/bird.ctl -d'

set container name bird volume conf destination '/etc/bird'
set container name bird volume conf source '/config/myapp/bird'

set system login banner post-login 'generated by tests'

echo 'configure done'

commit

# Download the generated BIRD config to a temp file in the SAME dir, syntax-check
# it, then swap it in atomically (mv = rename). A failed download OR a config
# that does not parse must never clobber the working bird.conf — we only reload
# BIRD once the new config is downloaded AND validated.
mkdir -p /config/myapp/bird
TMP_BIRD_CONF=$(mktemp /config/myapp/bird/.bird.conf.XXXXXX)
if curl -sSfL -o "$TMP_BIRD_CONF" "https://worker.example/kawaii/as27523/router/bird.core.test.example.conf"; then
    # /config/myapp/bird is mounted into the container at /etc/bird, so the temp
    # file is reachable there. `bird -p` is parse-only (does not touch the daemon).
    NEW_IN_CTR="/etc/bird/$(basename "$TMP_BIRD_CONF")"
    if ! sudo podman exec bird true 2>/dev/null; then
        # Container not up yet (first provision — it has no config to start with).
        # Can't pre-validate; place the config so BIRD can come up on next start.
        mv "$TMP_BIRD_CONF" /config/myapp/bird/bird.conf
    elif sudo podman exec bird bird -p -c "$NEW_IN_CTR"; then
        # Running and parses cleanly: swap in atomically and reload.
        mv "$TMP_BIRD_CONF" /config/myapp/bird/bird.conf
        sudo podman exec bird birdcl -s /etc/bird/bird.ctl configure || true
    else
        echo "new bird.conf failed 'bird -p' syntax check; keeping the existing config" >&2
        rm -f "$TMP_BIRD_CONF"
    fi
else
    echo "bird.conf download failed; keeping the existing config" >&2
    rm -f "$TMP_BIRD_CONF"
fi

# Host convenience: a `birdc` wrapper on PATH opens the container's BIRD client
# (works for any user, sudo and scripts, unlike a shell alias). Rewritten every
# run via tee, so it is idempotent and always reflects the current command.
sudo tee /usr/local/bin/birdc >/dev/null <<'EOF'
#!/bin/sh
exec sudo podman exec -it bird birdc -s /etc/bird/bird.ctl "$@"
EOF
sudo chmod +x /usr/local/bin/birdc

exit
